<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoteVault.DAL\NoteVault.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Notes\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
